### PR TITLE
Read number of backup files to keep from file

### PR DESCRIPTION
**Pull request by tjakob**
Use /etc/target/preferences files to store universal configurations
that are the same for all users.
Preference file has format of:
    key = value

### CODE REVIEW

**Comment by agrover** [comment]
Why?

**Comment by tjakob** [comment]
The main purpose is to be able to change the number of backup files we keep in /etc/target/backup. We don't want this saved in ~/.targetcli/prefs.bin with the other global preferences because if User A saves 50 backups, then User B runs a saveconfig without changing the number of backups, User A loses backup data.

**Comment by agrover** [comment]
Why would someone want to change the number of backup files? I'm trying to understand if we can avoid making this configurable by just changing the value, if it is too high or low.

**Comment by tjakob** [comment]
We want more backups (50 or so) so we are more likely to have old mappings if a customer loses mappings and tries to fix it themselves first (which could potentially run the saveconfig operation numerous times because of auto_save_on_exit)

**Comment by agrover** [comment]
OK, makes sense. Thanks for explaining. Can we change the file name to /etc/target/targetcli.conf?

**Comment by bgly** [comment]
@agrover Can we get this pushed through?

**Comment by agrover** [comment]
👍 Thanks bigly, @bgly!

**Comment by pkalever** [comment]
Please lake a look at https://github.com/open-iscsi/targetcli-fb/pull/99/commits/bd3b2b50d741848a748830d9a1a7ee642e8d40d3 attached to https://github.com/open-iscsi/targetcli-fb/pull/99

**Pull request merged**
